"""
Django settings for djproject project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import sys
from flask import Flask
app = Flask(__name__) 


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


sys.dont_write_bytecode = True

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9p%a7c*co*kv*f78$n+@8^$#ppzw2c9mh0alc+@9t^s&toxg3@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['ip134.puli27.ncnu.edu.tw','163.22.27.134']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'lineBotApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djproject.urls'
app.logger.info(os.path.join(BASE_DIR,'lineBotApp','templates'))
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates').replace('\\','/'),
                 os.path.join(BASE_DIR,'lineBotApp','templates')  ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'djproject.wsgi.application'
DJANGO_TABLES2_TEMPLATE = "django_tables2/bootstrap4.html"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}
DATABASES = {
    "default": {
        "ENGINE" : "django.db.backends.postgresql_psycopg2",
        "NAME": "postgres",
        'USER': 'qhfvjzcqqgbykn',
        'PASSWORD': 'eaa367e02a61a4dac21029cc54684143e35380c47dd8f2f69486dfdc7d2f85cd',
        #'HOST': 'ec2-3-224-8-189.compute-1.amazonaws.com',
        'HOST': '163.22.27.130',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'zh-hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICILES_DIRS = [
    os.path.join(BASE_DIR,'static'), #加入static路徑
    os.path.join(BASE_DIR,'static/bootstrap-icons-1.9.1/font'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_COOKIE_SECURE=True
SESSION_COOKIE_HTTPONLY=True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTOCOL', 'https')


# session expire at browser close
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# wsgi scheme
os.environ['wsgi.url_scheme'] = 'https'


#LINE_CHANNEL_ACCESS_TOKEN = 'JsxDdLf5cuphuUVuoGvujchNKUIXJ8EtPC8t9A2ScfS9CgtMNxshsmelb/DE6SxTm5k5M7W4ZEkwEHM51pAyusK9r7FN1JQJJ83xBs0efkt2gZ9JygTkh4Zpwg4pc48tsSHQMKc3uXwwsNankROK4wdB04t89/1O/w1cDnyilFU='
#LINE_CHANNEL_SECRET = '6c50569bec91e809674daf78228a4689'
LINE_CHANNEL_ACCESS_TOKEN = 'FN9aUD1hA2GqE0h4emQWsjyPzIMRIEM+xh6kVHJXjm6weD6F6vxlCOLZo2gC6RLwP9Q+1mHrNhyxyEtA6aj65nZHh+nOSsw0YfvFZ7Bah3x8ioThEKyYB2BiRxZdIN1Ytuv377kryazq922MPnFZJgdB04t89/1O/w1cDnyilFU='
LINE_CHANNEL_SECRET = 'a14a4b0d0561b02fb44f4501e6dbd5a3'


#LINE_CHANNEL_ID='1657441402'
LINE_CHANNEL_ID='1657224062'

SERVER_URL="https://ip134.puli27.ncnu.edu.tw/"


#app.logger.info(BASE_DIR)
